INSERT INTO department (name)
VALUES ('Sales'),
        ('Marketing'),
        ('Human Resources'),
        ('Engineering'),
        ('Technology'),
        ('Operations management'),
        ('Management'),
        ('Research and development'),
        ('Production'),
        ('Quality Assurance'),
        ('Law'),
        ('Product Management'),
        ('Asset management');

INSERT INTO role (title, salary, department_id)
VALUES ('Chief Operating Officer', 385000, 01),
        ('Chief Executive Officer', 430000, 02),
        ('Chief Financial Officer', 480000, 03),
        ('Chief Marketing Officer', 450000, 04),
        ('Chief Technology Officer', 425000, 05),
        ('Chief Information Officer', 430000, 06),
        ('Management', 150000, 07),
        ('Project manager', 290000, 08),
        ('President', 182000, 09),
        ('Chief Human Resources Officer', 286000, 10),
        ('Vice president', 195000, 11),
        ('Manager', 101000, 12),
        ('Account Manager', 86000, 13),
        ('Operations management', 166000, 14),
        ('General Manager', 178000, 15),
        ('Accountant', 185000, 16),
        ('Marketing management', 125000, 17),
        ('Administrative assistant', 68000, 18),
        ('Customer service representative', 67000, 19),
        ('Sales Management', 168000, 20),
        ('Chief Administrative Officer', 140000, 21),
        ('Sales Representative', 85000, 22),
        ('Product Manager', 98000, 23),
        ('Account Executive', 63500, 24);


INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Charles','Chandler'),
        ('Richard','Jones'),
        ('Abe','Sapien'),
        ('Emil','Blonsky'),
        ('Adam','Monroe'),
        ('Adam','Strange'),
        ('Sharon','Carter'),
        ('Christopher','Nord'),
        ('Gabriel','Lan'),
        ('Alan','Scott'),
        ('Alex','Mercer'),
        ('Alex','Woolsly'),
        ('Allan','Quatermain'),
        ('Ando','Masahashi'),
        ('Bernhard','Baker'),
        ('Henry','Pym'),
        ('Scott','Lang'),
        ('Jason','Wynn'),
        ('Edward','Brock'),
        ('Arthur','Curry'),
        ('Julia','Carpenter'),
        ('Warren','Worthington'),
        ('Hisako','Ichiki'),
        ('Roy','Harper'),
        ('Erik','Josten'),
        ('Albert','Pratt'),
        ('Raymond','Palmer'),
        ('Michael','Lane'),
        ('Sean','Cassidy'),
        ('Roberto','Velasquez'),
        ('Mary','Kane'),
        ('Barbara','Gordon'),
        ('Helena','Bertinelli'),
        ('Cassandra','Cain'),
        ('Stephanie','Brown'),
        ('Bruce','Wayne'),
        ('Richard','Grayson'),
        ('Terrence','McGinnis'),
        ('Lemar','Hoskins'),
        ('Henry','McCoy'),
        ('Garfield','Logan'),
        ('Ben','Kirby'),
        ('Ray','Bill'),
        ('Damon','Macready'),
        ('Frederick','Foswell'),
        ('Bill','Harken'),
        ('Billy','Kincaid'),
        ('Carol','Danvers'),
        ('Jamie','Sommers'),
        ('Lucas','Bishop'),
        ('Dinah','Lance'),
        ('Felicia','Hardy'),
        ('Jefferson','Pierce'),
        ('Tanya','Sealy'),
        ('Yelena','Belova'),
        ('Eric','Brooks'),
        ('Clarice','Ferguson'),
        ('Donald','Gill'),
        ('Sean','Dolan'),
        ('Daniel','Garrett'),
        ('Jaime','Reyes'),
        ('Tabitha','Smith'),
        ('Michael','Carter'),
        ('Madison','Jeffries'),
        ('Jericho','Drumm'),
        ('Seth','Brundle'),
        ('Anne','Summers'),
        ('Karen','Duncan'),
        ('Nathan','Summers'),
        ('Cameron','Hicks'),
        ('Steven','Rogers'),
        ('Nathaniel','Adam'),
        ('Brian','Braddock'),
        ('Leonard','Snart'),
        ('Jack','Brolin'),
        ('Frederick','Freeman'),
        ('Shirlee','Bryant'),
        ('Selina','Kyle'),
        ('Cecilia','Reyes'),
        ('Kevin','Sidney'),
        ('Priscilla','Rich'),
        ('Deborah','Domaine'),
        ('Claire','Bennet'),
        ('Tyrone','Johnson'),
        ('Colin','Wagner'),
        ('Vanessa','Carlysle'),
        ('Victor','Stone'),
        ('Henry','Henshaw'),
        ('Scott','Summers'),
        ('Danny','Cooper'),
        ('Anakin','Skywalker'),
        ('Victor','vonDoom'),
        ('Otto','Octavius'),
        ('Stephen','Strange'),
        ('Neena','Thurman'),
        ('Ethan','Hunt'),
        ('Fabian','Cortez'),
        ('Samuel','Wilson'),
        ('Angelica','Jones'),
        ('Paul','Ebersol'),
        ('Peter','Garrick');
