INSERT INTO department (name)
VALUES ("Sales"),
       ("Marketing"),
       ("Human Resources"),
       ("Engineering"),
       ("Management"),
       ("Production");

INSERT INTO role (title, salary, department_id)
VALUES ("Chief Executive Officer", 450000, 5),
        ("Chief Marketing Officer", 430000, 2),
        ("Chief Technology Officer", 425000, 4),
        ("Chief HR Officer", 286000, 3),
        ("Account Manager", 86000, 1),
        ("Operations management", 166000, 6),
        ("Product Manager", 98000, 6),
        ("Marketing management", 125000, 2),
        ("Sales Representative", 85000, 1),
        ("Accountant", 185000, 5),
        ("Chief Administrative Officer", 140000, 3),
        ("Product Engineer", 168000, 4),
        ("Customer service rep", 67000, 1);

INSERT into employee (first_name, last_name, role_id, manager_id)
VALUES ("John", "Johnson", 1, NULL),
        ("Carley", "Moore", 2, 1),
        ("Dena", "Wilson", 4, 1),
        ("David", "Peterson", 3, 2),
        ('Charles','Chandler', 6, 4),
        ('Emil','Blonsky', 7, 5),
        ('Adam','Monroe', 8, 2),
        ('Adam','Strange', 13, 7),
        ('Sharon','Carter', 8, NULL),
        ('Allan','Quatermain', 12, 9),
        ('Ando','Masahashi', 5, 8),
        ('Henry','Pym', 10, 11),
        ('Scott','Lang', 7, 6),
        ('Jason','Wynn', 12, 10),
        ('Edward','Brock', 8, 7),
        ('Arthur','Curry', 10, 13),
        ('Julia','Carpenter', 9, NULL),
        ('Hisako','Ichiki', 4, 11),
        ('Albert','Pratt', 6, 17),
        ('Sean','Cassidy', 9, 8),
        ('Mary','Kane', 13, 11),
        ('Barbara','Gordon', 13, 9),
        ('Cassandra','Cain', 5, 18),
        ('Stephanie','Brown', 1, NULL),
        ('Bruce','Wayne', 7, 16),
        ('Henry','McCoy', 9, 24),
        ('Garfield','Logan', 8, 11),
        ('Ben','Kirby', 6, 15),
        ('Ray','Bill', 9, 16),
        ('Damon','Macready', 6, 20),
        ('Bill','Harken', 11, 8),
        ('Carol','Danvers', 5, NULL),
        ('Jamie','Sommers', 12, 4),
        ('Felicia','Hardy', 13, NULL),
        ('Tanya','Sealy', 12, 7),
        ('Clarice','Ferguson', 9, 24),
        ('Tabitha','Smith', 6, 27),
        ('Michael','Carter', 2, 20),
        ('Seth','Brundle', 13, 27),
        ('Anne','Summers', 10, NULL),
        ('Karen','Duncan', 12, 39),
        ('Steven','Rogers', 8, 19),
        ('Jack','Brolin', 6, 27),
        ('Shirlee','Bryant', 7, 24),
        ('Selina','Kyle', 12, 17),
        ('Kevin','Sidney', 7, 36),
        ('Claire','Bennet', 3, 20),
        ('Scott','Summers', 12, 22),
        ('Anakin','Skywalker', 6, 27),
        ('Victor','vonDoom', 7, NULL),
        ('Otto','Octavius', 10, 27),
        ('Stephen','Strange', 5, 27),
        ('Ethan','Hunt', 8, 34),
        ('Angelica','Jones', 5, 27);